### ISSUE TITLE
Minimum sdk 19  is not supported 

### ISSUE THREAD

**Issue by piashcse** [psteiger/LocationFetcher#14]
Minimum sdk is not supported for 19 cause flow-lifecycle-observer minimum sdk is 21

is it possible to decrease flow-lifecycle-observer from 21 to 19 so that LocationFetcher can support sdk 19.

**Comment by psteiger** [comment]
Hi @piashcse ,

I have created an experimental version in a different branch with both this library and `flow-lifecycle-observer` set to `minSdkVersion 16`

You can use:

`        implementation 'com.github.psteiger:LocationFetcher:minsdk16-SNAPSHOT'`

If you end up testing it, feedback is welcome.

**Comment by psteiger** [comment]
Fixed in 6.0
